services:
  user-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: todaii-backend
    command: java -jar /jars/user-api.jar

    env_file:
      - ./apps/user-api/.env

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "8081:8081"

  admin-api:
    image: todaii-backend
    command: java -jar /jars/admin-api.jar

    env_file:
      - ./apps/admin-api/.env

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "8082:8082"

volumes:
  mysql_data: