package com.todaii.english.server.vocabulary;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.todaii.english.core.entity.VocabDeck;
import com.todaii.english.shared.request.server.DeckRequest;
import com.todaii.english.shared.response.PagedResponse;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Min;
import lombok.RequiredArgsConstructor;

@RestController
@RequiredArgsConstructor
@Validated
@RequestMapping("/api/v1/vocab-deck")
public class VocabDeckApiController {
	private final VocabDeckService vocabDeckService;
	private final VocabDeckGeneratorService vocabDeckGeneratorService;

	@Deprecated
	public ResponseEntity<List<VocabDeck>> getAllVocabDecks() {
		return ResponseEntity.ok(vocabDeckService.findAll());
	}

	@GetMapping
	public ResponseEntity<PagedResponse<VocabDeck>> getAllPaged(@RequestParam(defaultValue = "1") @Min(1) int page,
			@RequestParam(defaultValue = "10") @Min(1) int size, @RequestParam(defaultValue = "id") String sortBy,
			@RequestParam(defaultValue = "desc") String direction, @RequestParam(required = false) String keyword) {
		Page<VocabDeck> decks = vocabDeckService.findAllPaged(page, size, sortBy, direction, keyword);

		PagedResponse<VocabDeck> response = new PagedResponse<>(decks.getContent(), page, size,
				decks.getTotalElements(), decks.getTotalPages(), decks.isFirst(), decks.isLast(), sortBy, direction);

		return ResponseEntity.ok(response);
	}

	@GetMapping("/group/{groupId}")
	public ResponseEntity<PagedResponse<VocabDeck>> getDecksByGroupdId(@PathVariable Long groupId,
			@RequestParam(defaultValue = "1") @Min(1) int page, @RequestParam(defaultValue = "10") @Min(1) int size,
			@RequestParam(defaultValue = "id") String sortBy, @RequestParam(defaultValue = "desc") String direction,
			@RequestParam(required = false) String keyword) {
		Page<VocabDeck> decks = vocabDeckService.findByGroupId(groupId, page, size, sortBy, direction, keyword);

		PagedResponse<VocabDeck> response = new PagedResponse<>(decks.getContent(), page, size,
				decks.getTotalElements(), decks.getTotalPages(), decks.isFirst(), decks.isLast(), sortBy, direction);

		return ResponseEntity.ok(response);
	}

	@GetMapping("/{deckId}")
	public ResponseEntity<VocabDeck> getVocabDeck(@PathVariable Long deckId) {
		return ResponseEntity.ok(vocabDeckService.findById(deckId));
	}

	@PostMapping
	public ResponseEntity<VocabDeck> createDraftDeck(@Valid @RequestBody DeckRequest deckRequest) {
		return ResponseEntity.ok(vocabDeckService.createDraftDeck(deckRequest));
	}

	@PostMapping("/{deckId}/word/{wordId}")
	public ResponseEntity<VocabDeck> addWordToDeck(@PathVariable Long deckId, @PathVariable Long wordId) {
		return ResponseEntity.ok(vocabDeckService.addWordToDeck(deckId, wordId));
	}

	@PostMapping("/{deckId}")
	public ResponseEntity<VocabDeck> autoGenerateDeckWords(@PathVariable Long deckId) {
		return ResponseEntity.ok(vocabDeckGeneratorService.autoGenerateDeckWords(deckId));
	}

	@DeleteMapping("/{deckId}/word/{wordId}")
	public ResponseEntity<VocabDeck> removeWordFromDeck(@PathVariable Long deckId, @PathVariable Long wordId) {
		return ResponseEntity.ok(vocabDeckService.removeWordFromDeck(deckId, wordId));
	}

	@PutMapping("/{deckId}")
	public ResponseEntity<VocabDeck> updateVocabDeck(@PathVariable Long deckId,
			@Valid @RequestBody DeckRequest deckRequest) {
		return ResponseEntity.ok(vocabDeckService.updateVocabDeck(deckId, deckRequest));
	}

	@PatchMapping("/{deckId}/enabled")
	public ResponseEntity<Void> toggleEnabled(@PathVariable Long deckId) {
		vocabDeckService.toggleEnabled(deckId);
		return ResponseEntity.noContent().build();
	}

	@DeleteMapping("/{deckId}")
	public ResponseEntity<Void> deleteVocabDeck(@PathVariable Long deckId) {
		vocabDeckService.deleteById(deckId);
		return ResponseEntity.noContent().build();
	}
}
