package com.todaii.english.server.vocabulary;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.todaii.english.core.entity.VocabDeck;

import lombok.RequiredArgsConstructor;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1/vocab-deck-generator")
public class VocabDeckGeneratorApiController {
	private final VocabDeckGeneratorService vocabDeckGeneratorService;

	@PostMapping("/{deckId}")
	public ResponseEntity<VocabDeck> autoGenerateDeckWords(@PathVariable Long deckId) {
		return ResponseEntity.ok(vocabDeckGeneratorService.autoGenerateDeckWords(deckId));
	}

}
