server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 1
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: ${GEMINI_MODEL}
            temperature: 1
    retry:
      max-attempts: 1
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/chatbotSchema.sql

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER}
      secret: ${JWT_SECRET}

#gemini:
#  model: ${GEMINI_MODEL}
#  api:
#    key: ${GEMINI_API_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

google:
  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}